frontend:
  - changed-files:
      - any-glob-to-any-file: 'src/app/**/*'
      - any-glob-to-any-file: 'src/components/**/*'
      - any-glob-to-any-file: 'public/**/*'

core-logic:
  - changed-files:
      - any-glob-to-any-file: 'src/hooks/**/*'
      - any-glob-to-any-file: 'src/services/**/*'
      - any-glob-to-any-file: 'src/store/**/*'
      - any-glob-to-any-file: 'src/lib/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'src/app/api/**/*'

config:
  - changed-files:
      - any-glob-to-any-file: '*.config.mjs'
      - any-glob-to-any-file: '*.json'
      - any-glob-to-any-file: '.env*'
      - any-glob-to-any-file: 'pnpm-workspace.yaml'

automation:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'